#!/usr/bin/env python3

#   Copyright 2020 Google LLC

#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at

#       https://www.apache.org/licenses/LICENSE-2.0

#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

import argparse
import csv
import pathlib

import matplotlib.pyplot as plt

topdir = pathlib.Path(__file__).parent

def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('csv', nargs='*', type=pathlib.Path)
    parser.add_argument('--query', action='append')
    return parser.parse_args()

def meets_query(query, d):
    if query is None:
        return True
    for q in query:
        k, v = q.split("=", 1)
        if d[k] != v:
            return False
    return True

def main():
    args = parse_args()
    for path in args.csv:
        with path.open() as f:
            r = csv.DictReader(f)
            for d in r:
                if meets_query(args.query, d):
                    for k, v in d.items():
                        print(f"{k:>30}: {v}")
                    print()

if __name__ == "__main__":
    main()