#!/usr/bin/env python3

import argparse
import codecs
import csv
import itertools
import pathlib

topdir = pathlib.Path(__file__).parent

import matplotlib.pyplot as plt
import requests_cache

def get_incumbents():
    incumbents_rev = {
        "red": "ME IA NC MT LA CO GA AZ KS SC AK TX KY MS ID OK SD NE WV AR TN WY",
        "blue": "AL MI MN NM NH VA IL NJ OR DE MA RI"
    }
    incumbents = {}
    for k, v in incumbents_rev.items():
        for vv in v.split():
            if vv in incumbents:
                raise Exception("ow")
            incumbents[vv] = k
    return incumbents

def fec_fetch(session, url, params):
    for page in itertools.count(start=1):
        r = session.get(url, params=dict(page=str(page), **params))
        r.raise_for_status()
        d = r.json()
        #with open(f"/tmp/fec_{page:03}.json", "w") as f:
        #    json.dump(d, f, indent=4)
        yield from d['results']
        if page >= d['pagination']['pages']:
            break

def fec_totals(session):
    yield from fec_fetch(session, "https://api.open.fec.gov/v1/candidates/totals/", {
        'has_raised_funds': 'true',
        'api_key': 'DEMO_KEY',
        'office': 'S',
        'is_active_candidate': 'true',
        'election_full': 'true',
        'election_year': '2020',
    })

def get_receipts(session):
    receipts = {}
    for d in fec_totals(session):
        if d['party'] == "REP":
            continue
        state = d['state']
        receipts[state] = max(receipts.get(state, 0), d['receipts'])
    return receipts

def senate_toplines_deluxe(session):
    url = "https://projects.fivethirtyeight.com/2020-general-data/senate_state_toplines_2020.csv"
    with session.get(url, stream=True) as r:
        r.raise_for_status()
        done = set()
        for d in csv.DictReader(codecs.iterdecode(r.iter_lines(), 'utf-8')):
            if d['expression'] != '_deluxe':
                continue
            district = d['district']
            if district in done:
                continue
            done.add(district)
            yield d

def plot(session):
    incumbents = get_incumbents()
    receipts = get_receipts(session)
    fig = plt.figure()
    ax = fig.add_subplot(1,1,1)
    ax.autoscale(False)
    ax.set_xbound([-0.05, 1.05])
    ax.set_ybound([0, 1.1 * max(receipts.values())/1E6])
    ax.set_title("Senate seats, neglectedness and tractability")
    ax.set_xlabel("538 GOP probability (deluxe model)")
    ax.set_ylabel("FEC receipts by top non-GOP candidate ($M)")
    for d in senate_toplines_deluxe(session):
        rprob = float(d['winner_Rparty'])
        if abs(rprob - 0.50) > 0.49:
            continue
        state = d['district'][:2]
        ax.text(rprob, receipts[state]/1E6, state,
            ha="center", va="center", color=incumbents[state])

def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--outfile", type=pathlib.Path)
    return parser.parse_args()

def main():
    args = parse_args()
    session = requests_cache.core.CachedSession(expire_after=86400)
    plot(session)
    if args.outfile is not None:
        plt.savefig(str(args.outfile), dpi=300, backend='agg')
    else:
        plt.show()

if __name__ == "__main__":
    main()
